import { QuestDefinition } from '../models/quest';

export const QUEST_DEFINITIONS: QuestDefinition[] = [
  {
    questId: 'win_3_battles',
    type: 'win_battles',
    name: 'Victorious',
    description: 'Win 3 battles',
    target: 3,
    rewardGold: 200,
    rewardXp: 100,
    rewardGems: 5,
  },
  {
    questId: 'win_5_battles',
    type: 'win_battles',
    name: 'Battle Master',
    description: 'Win 5 battles',
    target: 5,
    rewardGold: 400,
    rewardXp: 200,
    rewardGems: 10,
  },
  {
    questId: 'complete_1_campaign',
    type: 'complete_campaign',
    name: 'Adventurer',
    description: 'Complete 1 campaign stage',
    target: 1,
    rewardGold: 150,
    rewardXp: 75,
    rewardGems: 5,
  },
  {
    questId: 'complete_3_campaigns',
    type: 'complete_campaign',
    name: 'Conqueror',
    description: 'Complete 3 campaign stages',
    target: 3,
    rewardGold: 300,
    rewardXp: 150,
    rewardGems: 10,
  },
  {
    questId: 'upgrade_hero_1',
    type: 'upgrade_hero',
    name: 'Hero Trainer',
    description: 'Upgrade a hero once',
    target: 1,
    rewardGold: 150,
    rewardXp: 75,
    rewardGems: 5,
  },
  {
    questId: 'upgrade_hero_3',
    type: 'upgrade_hero',
    name: 'Master Trainer',
    description: 'Upgrade heroes 3 times',
    target: 3,
    rewardGold: 300,
    rewardXp: 150,
    rewardGems: 10,
  },
  {
    questId: 'daily_login',
    type: 'login',
    name: 'Daily Check-in',
    description: 'Log in today',
    target: 1,
    rewardGold: 100,
    rewardXp: 50,
    rewardGems: 5,
  },
  {
    questId: 'spend_30_energy',
    type: 'spend_energy',
    name: 'Energetic',
    description: 'Spend 30 energy',
    target: 30,
    rewardGold: 200,
    rewardXp: 100,
    rewardGems: 5,
  },
];
